OpenUniversity/urls.py
from django.contrib import admin
from django.urls import path, include

#dadasdasds

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course_lesson.urls', namespace='course_lesson')),
    path('course/<int:course_id>/module/<int:module_id>/', include('ttest.urls', namespace='ttest')),
    path('', include('signin_signup.urls', namespace='signin_signup')),
    path('', include('pages.urls', namespace='pages')),
    path('', include('user_profile.urls', namespace='user_profile')),
    
]

pages/urls.py
from django.urls import path
from . import views

app_name='pages'

urlpatterns = [
    path('', views.index, name='index'),

]

signin_signup/urls.py
from django.urls import path
from . import views

app_name='signin_signup'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('check/', views.check, name='check'),
    path('logout/', views.logout, name='logout')

]

user_profile/urls.py
from django.urls import path
from . import views

app_name='user_profile'

urlpatterns = [
    path('profile/', views.profile, name='profile'),

]

templates/includes/footer.html
{% load static %}
{% block content %}
    <!-- Footer -->
	<section id="footer">
		<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-4" href="#">
					<img src="{% static 'img/Logo.png' %}" width="245" height="70" alt=""><span class="sr-only">(current)</span></img>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Ссылки на разделы:</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Контакты</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Организация</a></li>
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Лицензия</a></li>
					</ul>
				</div>

				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Партнеры:</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Татнефть</a></li>
					</ul>
				</div>

				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
						<ul class="list-unstyled list-inline social text-center">
							<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i> </a></li>
							<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
							<li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
							<li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
						</ul>
					</div>
				</div>
			<!--<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
					<p><u><a href="https://www.nationaltransaction.com/">National Transaction Corporation</a></u> is a Registered MSP/ISO of Elavon, Inc. Georgia [a wholly owned subsidiary of U.S. Bancorp, Minneapolis, MN]</p>
					<p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Sunlimetech</a></p>
				</div>
				</hr>
			</div>	-->

           <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


		</div>
        </div>
	</section>
{% endblock %}

templates/includes/header.html
{% load static %}
{% block content %}
<!-- Header -->
	<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #71c2dc;">
		<div class="ml-5">
	  <a class="navbar-brand" href="{% url 'pages:index' %}">
        <img src="{% static 'img/Logo.png' %}" width="90" height="27" alt=""><span class="sr-only">(current)</span></img>
  	  </a>
  	  </div>
	  <button class="navbar-toggler mr-5" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <!-- Кнопки в Header -->
	  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	    <ul class="navbar-nav mr-3 ml-auto">
	      <li class="nav-item">
	        <a class="nav-link" id="first" href="#">Курслар</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link yth" href="#">Проект турында</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Экспертлар</a>
	      </li >
            <li class="nav-item">
                <form class="form-inline my-2 my-lg-0">
	                <input class="form-control mr-sm-2" type="search" placeholder="Эзләү">
	             </form>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item mr-5">

            <!-- Example single danger button -->
                <div class="btn-group">
                  <button type="button" class="btn btn-success dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.first_name }}
                  </button>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'user_profile:profile'%}">Личный кабинет</a>
                    <a class="dropdown-item" href="#">Настройки профиля</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'signin_signup:logout' %}">Выйти</a>
                  </div>
                </div>
            </li>
            {% else %}
             <li class="nav-item mr-5">

             <a href="{% url 'signin_signup:sign_in' %}"><button class="btn shadow-sm rounded btn-outline-success my-2 my-sm-0" id="signinbtn" type="submit">Керү</button></a>
            </li>

            {% endif %}
	    </ul>


	  </div>
	</nav>
{% endblock %}