OpenUniversity/urls.py
from django.contrib import admin
from django.urls import path, include

#dadasdasds

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('course_lesson.urls', namespace='course_lesson')),
    path('course/<int:course_id>/module/<int:module_id>/', include('ttest.urls', namespace='ttest')),
    path('', include('signin_signup.urls', namespace='signin_signup')),
    path('', include('pages.urls', namespace='pages')),
    path('', include('user_profile.urls', namespace='user_profile')),
    
]

pages/urls.py
from django.urls import path
from . import views

app_name='pages'

urlpatterns = [
    path('', views.index, name='index'),

]

signin_signup/urls.py
from django.urls import path
from . import views

app_name='signin_signup'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('check/', views.check, name='check'),
    path('logout/', views.logout, name='logout')

]

signin_signup/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

signin_signup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import validate_email


class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class': "form-control", 'placeholder':"Введите ваш никнейм"}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': "form-control", 'placeholder':"Введите ваш email"}))
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': "form-control", 'placeholder':"Введите ваше имя"}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': "form-control", 'placeholder':"Введите фамилию"}))
    password1 = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': "form-control", 'placeholder':"Введите пароль", 'type':"password" }))
    password2 = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': "form-control", 'placeholder':"Введите пароль заново", 'type':"password" }))

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['email']

        if commit:
            user.save()


    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                if len(password2)<8:
                    raise forms.ValidationError('Пароль должен содержать минимум 8 символов')
                elif password2.isdigit():
                    raise forms.ValidationError('Пароль не должен состоять только из цифр')
                else :
                    return password2
        raise forms.ValidationError('Пароли не совпадают')

    def clean_email(self):
        email = self.cleaned_data['email']

        try:
            mt = validate_email(email)
            try:
                user = User.objects.filter(email=email)
                if (len(user)!=0):
                    raise forms.ValidationError('Пользователь с таким emailом существует')
            except User.DoesNotExist:
                return email
        except:
            raise forms.ValidationError('E-mail введен не корректно')

        return email

    def clean_username(self):
        username = self.cleaned_data['username']

        try:
            user = User.objects.filter(username=username)
            if (len(user) != 0):
                raise forms.ValidationError('Пользователь с таким никнеймом существует')
        except User.DoesNotExist:
            return username
        return username




class LoginForm (forms.Form):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={ 'class':"form-control", 'id':"inputEmail" ,'placeholder':"E-mail"}))
    password = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'type':"password", 'name':"password", 'class':"form-control", 'id':"inputPassword", 'placeholder':"Password"}))

    def clean_username(self):
        username = self.cleaned_data['username']

        if '@' in username:
            try:
                user = User.objects.filter(email=username)
                if len(user) == 1:
                    user = user.first()
                    return user.username
                elif len(user) > 1:
                    raise forms.ValidationError("Попробуйте, пожалуйста, войти через username")
                else:
                    raise forms.ValidationError("Пользователь не найден! Пожалуйста, проверьте корректность введенных данных!")
            except User.DoesNotExist:
                raise forms.ValidationError("Пользователя с таким емаилом не существует")

        return username

signin_signup/views.py
from django.shortcuts import render, render_to_response
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.template.context_processors import csrf


# Create your views here.


def sign_in(request):
    return render(request, 'signin_signup/sign_in.html')


def sign_up(request):
    return render(request, 'signin_signup/sign_up.html')

# def login1(request):
# 	if request.user.is_authenticated:
# 		return render(request, 'signin_signup/check.html')
# 	else:
# 		args = {}
# 		args.update(csrf(request))
# 		if request.POST:
# 			username = request.POST.get('email', '')
# 			password = request.POST.get('password', '')
# 			user = auth.authenticate(username=username, password=password)
# 			if user is not None:
# 				auth.login(request, user)
# 				return HttpResponseRedirect(reverse('check'))
# 			else:
# 				args['login_error'] = "User is not found"
# 				return render_to_response('signin_signup/sign_in.html', args)
# 		else:
# 			return render_to_response('signin_signup/sign_in.html', args)

signin_signup/templates/signin_signup/check.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ user.username }}
    {{ user.email }}
    {{ user.name }}
</body>
</html>

signin_signup/templates/signin_signup/sign_in.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Вход</title>

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'signin_signup/css/sign_in.css' %}" rel="stylesheet">
    <link href="{% static 'css/includes/footer.css' %}" type="text/css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

  </head>
  <body>
    <div class="container">
     <div class="row">
       <div class="col-md-offset-3 col-md-6">
       <form class="form-horizontal" method="POST" action="">
           {% csrf_token %}
        <div class="justify-content-center pt-5" >

            <img src="{% static 'img/Logo.png' %}" width="230" height="70" alt=""><span class="sr-only">(current)</span></img>

        </div>
        <span class="heading">Теркәлү сорала</span>
        <div class="form-group">
            {{ form.username }}
            {% if form.username.errors %}
               <div class="alert alert-danger mr-3 ml-3" role="alert">
                  {{ form.username.errors }}
              </div>
           {% endif %}
            <!--
          <input name="email" class="form-control" id="inputEmail" placeholder="E-mail">-->
          <i class="fa fa-user"></i>
        </div>

       <div class="form-group help">
           {{ form.password }}
           {% if form.password.errors %}
               <div class="alert alert-danger mr-3 ml-3" role="alert">
                  {{ form.password.errors }}
              </div>
           {% endif %}
           <!--
         <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Password">-->
         <i class="fa fa-lock"></i>
         <a href="#" class="fa fa-question-circle"></a>
       </div>

       <div class="form-group">
         <div class="main-checkbox">

          <input type="checkbox" value="none" id="checkbox1" name="check"/>
          <label for="checkbox1"></label>
         </div>
        <span class="text">Истә калдырырга</span>
        <button type="submit" class="btn btn-default">ВХОД</button>
      </div>

           {% if error_message %}
              <div class="alert alert-danger mr-3 ml-3" role="alert">
                  {{ error_message }}
              </div>
           {% endif %}
      <div class="mb-5">
       <a href="{% url 'signin_signup:sign_up' %}"class="btn btn-primary btn-lg btn-block">Зарегистрироваться</a>
      </div>


      </form>
      </div>
     </div>
    </div>
  </body>
</html>

signin_signup/templates/signin_signup/sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Регистрация</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'signin_signup/css/sign_up.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
<div class="container">
    <div class="row main-form">
        <form class="" method="post" action="#">
        {% csrf_token %}
            <figure class="fig">
                <img src="{% static 'img/Logo.png' %}" width="230" height="70" alt=""><span
                    class="sr-only">(current)</span></img>
            </figure>

            <h1 align="center" style="color:White">Регистрация</h1>
            <div class="form-group">
                <label for="name" class="cols-sm-2 control-label">Ваше Имя</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                        {{ form.first_name }}

                    </div>
                    {% if form.first_name.errors %}
                            <div class="alert alert-danger mr-3 ml-3" role="alert">
                                {{ form.first_name.errors }}
                            </div>
                        {% endif %}
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="cols-sm-2 control-label">Ваша Фамилия</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                        {{ form.last_name }}

                    </div>
                    {% if form.last_name.errors %}
                            <div class="alert alert-danger mt-1" role="alert">
                                {{ form.last_name.errors }}
                            </div>
                        {% endif %}
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="cols-sm-2 control-label">Ваш никнейм</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                        {{ form.username }}

                    </div>
                    {% if form.username.errors %}
                            <div class="alert alert-danger mt-1" role="alert">
                                {{ form.username.errors }}
                            </div>
                        {% endif %}
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="cols-sm-2 control-label">Ваш Email</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                        {{ form.email }}


                    </div>
                    {% if form.email.errors %}
                            <div class="alert alert-danger mt-1" role="alert">
                                {{ form.email.errors }}
                            </div>
                        {% endif %}
                </div>
            </div>

            <div class="form-group">
                <label for="password" class="cols-sm-2 control-label">Пароль</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                        {{ form.password1 }}

                    </div>
                    {% if form.password1.errors %}
                            <div class="alert alert-danger mt-1" role="alert">
                                {{ form.password1.errors }}
                            </div>
                        {% endif %}
                </div>
            </div>

            <div class="form-group">
                <label for="confirm" class="cols-sm-2 control-label">Повтор Пароля</label>
                <div class="cols-sm-10">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                         {{ form.password2 }}
                    </div>
                    {% if form.password2.errors %}
                            <div class="alert alert-danger mt-1" role="alert">
                                {{ form.password2.errors }}
                            </div>
                        {% endif %}
                </div>
            </div>

            <div class="form-group ">
                <div class="mb-5">
                    <button type="submit" class="btn btn-default">Создать аккаунт</button>
                </div>
            </div>

        </form>
    </div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>